#!/usr/bin/env python3
"""Regenerate issues.json and issues.js from individual issue .md files.

Run from anywhere:
    python3 issues/generate.py
    cd issues && python3 generate.py
"""

import re, os, json

issues_dir = os.path.dirname(os.path.abspath(__file__))


def extract_field(content, field):
    m = re.search(r'\|\s*\*\*' + field + r'\*\*\s*\|\s*(.+?)\s*\|', content)
    return m.group(1).strip() if m else ""


def extract_description(content):
    m = re.search(r'## Description\s+(.+?)(?=\n##|\Z)', content, re.DOTALL)
    return m.group(1).strip() if m else ""


issues = []
for fname in sorted(f for f in os.listdir(issues_dir) if re.match(r'^\d{4}\.md$', f)):
    path = os.path.join(issues_dir, fname)
    with open(path, encoding="utf-8") as f:
        content = f.read()

    num = fname.replace(".md", "")
    title_m = re.search(r"^# \d+ — (.+)", content, re.MULTILINE)
    title = title_m.group(1).strip() if title_m else ""

    issues.append({
        "id": num,
        "title": title,
        "status": extract_field(content, "Status"),
        "module": extract_field(content, "Module"),
        "platform": extract_field(content, "Platform"),
        "first_seen": extract_field(content, "First seen"),
        "closed": extract_field(content, "Closed"),
        "description": extract_description(content),
    })

json_path = os.path.join(issues_dir, "issues.json")
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(issues, f, indent=2, ensure_ascii=False)
    f.write("\n")

js_path = os.path.join(issues_dir, "issues.js")
with open(js_path, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by generate.py — do not edit by hand */\n")
    f.write("window.ISSUES_DATA = ")
    json.dump(issues, f, indent=2, ensure_ascii=False)
    f.write(";\n")

print(f"Generated {len(issues)} issues → issues.json + issues.js")
